### ISSUE TITLE
Installation Documentation

### ISSUE THREAD

**Issue by TungstenE2** [pdreker/fritz_exporter#60]
Hi all,

I am trying to install fritz_exporter using Docker on my Synology NAS in order to read my Fritzbox 7490.

I am struggeling with the setup.

I created a NAS Folder: docker/fritzexporter and copied fritz-exporter.yml

content of  fritz-exporter.yml

```
# Config File for Fritz-Exporter
#exporter_port: 9787 # optional
#log_level: DEBUG # optional
devices:
  - name: Fritz!Box 7490 # optional
    hostname: fritz.box
    username: Fritz-Exporter
    password: Fritz-Exporter
```

But I am not sure how to mount the config file. In the documentation is not mentioned to which mount path the yml should be mounted.

https://github.com/pdreker/fritz_exporter/commit/f79cf402831a8c5092aa0eb18574f7e3e74065a9

![grafik](https://user-images.githubusercontent.com/39955685/118088766-d9ddfd00-b3c7-11eb-866e-9daec424bd6f.png)

![grafik](https://user-images.githubusercontent.com/39955685/118089083-43f6a200-b3c8-11eb-8a4a-0bc1230f1dd9.png)

Can you please support me and updated the installation documentation?

Thx
